
name: Build and deploy to zerops.io

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2     
    - name: install, build, deploy  
      env: 
        ZEROPSLOGIN: ${{ secrets.ZEROPSLOGIN }}       
        ZEROPSPASSWORD: ${{ secrets.ZEROPSPASSWORD }}        
      run: |
        npm ci
        npm run build
        # download CLI, save as zcli, set permissions
        wget -O zcli https://github.com/zeropsio/zcli/releases/download/v0.16/zcli-linux && chmod +x zcli
        ./zcli login
        ./zcli deploy test-app strapi .
